services:
  database:
    container_name: db-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - cr-network
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    container_name: cr-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    networks:
      - cr-network
    environment:
      - PORT=4000
      - DB_URL_MONGO=mongodb://db-mongo:27017/products/
      - JWT_PASS=2b$10$pNTpj97J9/iJbM8M8skoTe4yLSmER771j
    depends_on:
      - database

  frontend:
    container_name: cr-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_URL_GET_PRODUCTS_PROD
    ports:
      - "3000:3000"
    volumes:
      - cr-frontend-volume:/var/www/html
    networks:
      - cr-network
    restart: always
    depends_on:
      - backend

  nginx:
    container_name: cr-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - cr-network
    volumes:
      - cr-frontend-volume:/var/www/html
    restart: always
    depends_on:
      - frontend

networks:
  cr-network:
    driver: bridge

volumes:
  mongo-data:
  cr-frontend-volume:
