services:
  database:
    container_name: db-mongo

    image: mongo:latest

    ports:
      - "27017:27017"

    networks:
      - cr-network

    volumes:
      - mongo-data:/data/cr-db

    restart: always

  backend:
    container_name: cr-backend

    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "4000:4000"

    restart: always

    networks:
      - cr-network

    environment:
      - PORT=4000
      - DB_URL_MONGO=mongodb://db-mongo:27017/products/

    depends_on:
      - database

  frontend:
    container_name: cr-frontend

    volumes:
      - cr-frontend-volume:/var/www/html

    build:
      context: frontend
      dockerfile: Dockerfile

    environment:
      - VITE_URL_GET_PRODUCTS_PROD=http://localhost:4000/products
      - VITE_URL_GET_UPLOADS_PROD=http://localhost:4000/upload

    networks:
      - cr-network

    restart: always

  nginx:
    container_name: cr-nginx

    volumes:
      - cr-frontend-volume:/var/www/html

    build:
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - 80:80

    networks:
      - cr-network

    restart: always

    depends_on:
      - backend
      - database

networks:
  cr-network:
    driver: bridge

volumes:
  mongo-data:
  cr-frontend-volume:
